name: Basic Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  ci:
    name: Lint & Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Pixi
        uses: prefix-dev/setup-pixi@v0.8.1
        with:
          cache: true

      - name: Show Pixi environment
        run: |
          pixi info
          pixi list --locked
        shell: bash

      - name: Run pre-commit
        run: |
          pixi run pre-commit-install
          pixi run pre-commit-run
        shell: pixi run bash -e {0}

      - name: Generate & validate schemas
        run: |
          pixi run schemas
          pixi run validate-schemas
        shell: pixi run bash -e {0}

      - name: Lint (mypy)
        run: |
          pixi run lint
        shell: pixi run bash -e {0}

      - name: Run tests
        run: |
          pixi run test
        shell: pixi run bash -e {0}
